### ISSUE TITLE
puml-plantuml-jar-path 被转义导致出错。

### ISSUE THREAD

**Issue by lixuzhang** [skuro/puml-mode#19] opened 2016-04-29 15:09 UTC
1、必须在加载前设置好 puml-plantuml-jar-path ，否则出错。

2、我在emacs配置文件中设置了
(setq puml-plantuml-jar-path (locate-file "plantuml.jar" exec-path))
得到实际值为  f:/msys64/opt/bin/plantuml.jar
然后编辑准备C-c C-c生成图时，导致出错：
Error: Unable to access jarfile f\\:/msys64/opt/bin/plantuml.jar

查看代码，发现是 (shell-quote-argument puml-plantuml-jar-path) 导致转义，能否去掉 shell-quote-argument ？

**Comment by skuro** [comment] 2016-05-30 13:32
Mhhhh.. I'm sorry but I cannot read Chinese :-/
If Google Translates doesn't lie, you're having issues with setting the the path to the PlantUML jar in a Windows environment. Unfortunately this is still open (see #14), until that's fixed you can already find some workarounds in #10.

I'm closing the issue here, assuming this is a duplicate of #14.

**Closed by skuro** 2016-05-30 13:32 UTC
